# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BananaATVBrowser' do
  #pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'SVProgressHUD'
  pod 'TVVLCKit'
  #pod "TVVLCPlayer", :git => "https://github.com/kodlian/TVVLCPlayer.git", :tag => "1.1.1"
end
